"""
Run k-nearest neighbor classification with the embeddings generated by the model. 
"""
import argparse
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as metrics


def get_args():
    parser = argparse.ArgumentParser('python')

    parser.add_argument('-embedding_dir',
                        default='../embeddings/',
                        required=False,
                        help='text file to get the cluster labels') 

    parser.add_argument('-run',
                        default=27,
                        required=False,
                        help="which run's embedding to use")                        

    return parser.parse_args()

if __name__=="__main__":
    args = get_args()
    embedding_dir = args.embedding_dir
    run = args.run
    embedding_dir = embedding_dir + 'run_' + str(run) + '/'
    train_embedding_path = embedding_dir + 'train' + str(run) + '_embedding.npy'
    train_label_path = embedding_dir + 'train' + str(run) + '_label.npy'
    val_embedding_path = embedding_dir + 'val' + str(run) + '_embedding.npy'
    val_label_path = embedding_dir + 'val' + str(run) + '_label.npy'

    print('training embeddings:', train_embedding_path) 
    print('training label:', train_label_path) 
    print('val embeddings:', val_embedding_path) 
    print('val label:', val_label_path) 

    train_embedding = np.load(train_embedding_path)
    train_label = np.load(train_label_path)
    val_embedding = np.load(val_embedding_path)
    val_label = np.load(val_label_path)

    knn = KNeighborsClassifier(n_neighbors=5, n_jobs=4)
    knn.fit(train_embedding, train_label)

    train_prediction = knn.predict(train_embedding)
    val_prediction = knn.predict(val_embedding)
    train_acc = metrics.accuracy_score(train_label, train_prediction)
    val_acc = metrics.accuracy_score(val_label, val_prediction)
    print('train accuracy: {}, validation accuracy: {}'.format(train_acc, val_acc))