#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -A loni_omics02
#PBS -j oe

#source activate graph
source activate sci-comp
#cd /work/derick/siamese-monet-project/Siamese-MoNet/baseline-vina/
cd /work/wshi6/projects/siamese-monet-project/Siamese-MoNet/baseline-vina/

log_path="../../vina/vina-logs/vina-log-${LABEL}-${START}-${END}"

python dock.py -which_class ${LABEL} -start ${START} -end ${END} > ${log_path} 2>&1



